### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by ghost** [heitor31415/LearnSubtitles#1]
`import LearnSubtitles as ls

language = "de" # "pt" and "en" also available
my_sub = ls.LearnSubtitles("your/srt/file.srt", language)
print(my_sub.subtitle_path, my_sub.film_level)
print(*my_sub.easy_words, sep=", ")
print(*my_sub.intermediate_words, sep=", ")
print(*my_sub.advanced_words, sep=", `")`
I created as you said in readme but it doesn't show levels and I wanna extract that words as txt or similar settings. Could you help me? and how can I do it for multiple files at the same time.
Here's for example regarding that problem:
https://pastebin.com/vwZg3HnH

**Comment by heitor31415** [comment]
It seems that the output is already divided into the levels that I have set [here](https://github.com/heitor31415/LearnSubtitles/blob/153178ea11d700a49a1f3692de39e8fc81e3cc4e/LearnSubtitles.py#L153). You can change it accordingly. You can also put a `print("Easy words\n")`  if you need a clear separation. 
To use it in multiple files you have to create an instance for each file. You can use a comprehension list for that, I have done it in the test file, you can check it there.
